name: Bug Report
description: Something is not working right here..
labels: "bug"
assignees: "TheM1ddleM1n"
body:
  - type: input
    attributes:
      label: Which file?
      description: The name of the file that has the bug.
      placeholder: atari.py
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How do we make the bug happen?
      placeholder: |
        1. Ran atari.py in my terminal (via cmd terminal)
        2. Saw the Pygame window pop up
        3. Game couldn't run because of an error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: |
        The game should run smoothly
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: I am not omniscient so what actually happened?
      placeholder: |
        The game crashed with a Syntax Error/Logic Error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error Output
      description: Paste any error messages from your terminal.
  - type: input
    attributes:
      label: OS/Python Version
      description: Your OS and Python version (run `python --version`)
      placeholder: ie. Windows 11, Python 3.12
  - type: textarea
    attributes:
      label: Additional Information
      description: "Anything else that might help. Pro tip: 'please fix this bug' will NOT help."
