name: Bug Report
description: Something is not working.
labels: "bug"
assignees: "TheM1ddleM1n"
body:
  - type: input
    attributes:
      label: Which file?
      value: "atari.py"
      disabled: true
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How do we make the bug happen?
      placeholder: |
        1. Ran atari.py in my own terminal
        2. Saw the Pygame window pop up
        3. Game couldn't run because of an error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: |
        The game should have no errors
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: Tell me what happened?
      placeholder: |
        The game crashed with a Syntax/Logic Error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error Output
      description: Paste any error messages from your terminal.
  - type: input
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g. Windows 11, MacOS Sequoia, Ubuntu 24.04
    validations:
      required: true
  - type: input
    attributes:
      label: Python Version
      value: "3.13"
      disabled: true
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: "Anything else? Pro tip: 'please fix this bug' will NOT help."
