name: I would like to contribute!
description: Let me know you're working on something before you open a PR
labels: "contribution"
assignees: "TheM1ddleM1n"
body:
  - type: input
    attributes:
      label: What are you adding?
      description: TheM1ddleM1n cannot mind read so tell him a short description of what you add/remove.
      placeholder: Streamlined performance
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: Optional draft here
