name: Run Python Game

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (if any)
      run: |
        pip install -r requirements.txt || echo "No requirements.txt found"

    - name: Run game
      run: |
        python atari.py
