name: Run Python Game

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-mixer-2.0-0 libsdl2-dev libasound2-dev

    - name: Install Python dependencies
      run: |
        pip install pygame

    - name: Run Python Game with dummy audio
      env:
        SDL_AUDIODRIVER: dummy
      run: |
        python atari.py
