name: Execute atari.py

on:
  push:
    branches:
      - main
    paths:
      - "atari.py"
      - "requirements.txt"
  pull_request:
    branches:
      - main
    paths:
      - "atari.py"
      - "requirements.txt"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Python syntax only
        run: |
          python -m py_compile atari.py
          echo "Syntax check passed!"
