name: Run Python Game

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pygame
      run: |
        pip install pygame

    - name: Run game (without sound)
      env:
        CI: true  # مشخص می‌کنه که این اجرا در محیط CI هست
      run: |
        python atari.py
